{{- if and .Values.elasticsearch.enabled .Values.elasticsearch.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "elk.fullname" . }}-elasticsearch
  labels:
    {{- include "elk.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.elasticsearch.persistence.size }}
  {{- if .Values.elasticsearch.persistence.storageClass }}
  storageClassName: {{ .Values.elasticsearch.persistence.storageClass }}
  {{- end }}
{{- end }}
