{{- if .Values.kibana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elk.fullname" . }}-kibana
  labels:
    {{- include "elk.labels" . | nindent 4 }}
    app.kubernetes.io/component: kibana
spec:
  replicas: {{ .Values.kibana.replicas }}
  selector:
    matchLabels:
      {{- include "elk.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kibana
  template:
    metadata:
      labels:
        {{- include "elk.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kibana
    spec:
      containers:
      - name: kibana
        image: "{{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}"
        imagePullPolicy: {{ .Values.kibana.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 5601
          protocol: TCP
        env:
        {{- range .Values.kibana.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.kibana.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /api/status
            port: 5601
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/status
            port: 5601
          initialDelaySeconds: 90
          periodSeconds: 30
{{- end }}
